version: "3"

services:
  front:
    container_name: front
    build: ./frontend
    ports:
      - "8080:8080"
    network_mode: host
    depends_on:
      - backend

  backend:
    container_name: backend
    build: ./backend
    network_mode: host
    ports:
      - "5000:5000"